export enum BackgroundTaskAction {
    DID_MOUNT = "DID_MOUNT",
    WILL_UNMOUNT = "WILL_UNMOUNT",
    ADD_BUTTON = "ADD_BUTTON",
    REMOVE_BUTTON = "REMOVE_BUTTON",
    REMOVE_ALL_BUTTON = "REMOVE_ALL_BUTTON"
}
